### ISSUE TITLE
v0.7.1 conflicts with html5 canvas drawn objects, v0.4.1 doesn't

### ISSUE THREAD

**Issue by csa12** [harthur/color#33]
I've tested  with color-0.4.1.min.js and this works nicely with html5 canvas objects (context.rect(x, y, w, h)).

When replacing with color-0.7.1.min.js, objects on the html5 canvas get distorted. So the color script somehow conflicts with the drawing of objects on the html5 canvas.

**Comment by MoOx** [comment]
Can you provide some code or an living example in order to debug this plz?

**Comment by MoOx** [comment]
No feedback in 1 month, closing.
