### ISSUE TITLE
Remove bower & component.json or automate version bump

### ISSUE THREAD

**Issue by MoOx** [harthur/color#52]
Version in bower.json & component.json is clearly outdated.

Any watchers who still use bower or component(1) ?
Otherwise I'm wondering if we should just stop supporting this 2.
I think this 2 packages managers can use package.json, do they?

**Comment by ZuBB** [comment]
I am vote for this 

> automate version bump

with help of [grunt-release](https://github.com/geddski/grunt-release) or [grunt-bump](https://github.com/vojtajina/grunt-bump/)

**Comment by MoOx** [comment]
or just using [mversion](https://github.com/mikaelbr/mversion) cli :p

**Comment by ZuBB** [comment]
Oh, I see that you are going to drop grunt. then you picked up better tool
