### ISSUE TITLE
Conflict

### ISSUE THREAD

**Issue by trinzia** [harthur/color#6]
Hi,
Just a heads up - 
I wanted to try your script with the ColorPicker in Wordpress called Iris.  However, there appear to be naming conflicts, because when I import it, it breaks Iris.  This might be a common use-case for your script, so I thought you should know.

http://automattic.github.com/Iris/

Thanks.

**Comment by MoOx** [comment]
To avoid conflict, you should use commonjs style loader like browserify or webpack.
