### ISSUE TITLE
Unable to parse color from string "rgba(255,255,255,0.15 25%)"

### ISSUE THREAD

**Issue by andreypopp** [harthur/color#62]
This is what I get when trying to bundle twitter bootstrap with webpack in optimizing mode.

**Comment by iamstarkov** [comment]
cannot reproduce
```js
var color = require('color');
color('rgba(255,255,255,0.15)'); /* { values:
   { rgb: [ 255, 255, 255 ],
     hsl: [ 0, 0, 100 ],
     hsv: [ 0, 0, 100 ],
     hwb: [ 0, 100, 0 ],
     cmyk: [ 0, 0, 0, 0 ],
     alpha: 0.15 } }
*/
```

**Comment by MoOx** [comment]
From what I see in twitter bootstrap, there is a parenthesis before 25%.
https://github.com/twbs/bootstrap/blob/83bfff7f0765503b990b96c303eef67009e48d77/dist/css/bootstrap-theme.css#L498
How did you get this color `rgba(255,255,255,0.15 25%)` ? It's not valid CSS.

**Comment by andreypopp** [comment]
OK, sorry, I've got that from some older version of bootstrap. Now I've updated and the error is gone.

**Comment by iamstarkov** [comment]
👍
