### ISSUE TITLE
Calling color breaks in io.js v2.4.0 (npm v2.13.0)

### ISSUE THREAD

**Issue by franceindia** [harthur/color#69]
Hi,

Calling the color node module seems to break things in io.js and possibly npm 2.13.0.  This is before I even try to use any of its functionality, just calling the module like so triggers the following error:  
``` jsx
import Color from 'color'

```

I tried uninstalling and reinstalling it. Here is the error message:

```
ERROR in ./~/color/~/color-string/~/color-name/index.json
Module parse failed: /Users/~/git/xyz-repo/node_modules/color/node_modules/color-string/node_modules/color-name/index.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
| 	"aliceblue": [240, 248, 255],
| 	"antiquewhite": [250, 235, 215],
| 	"aqua": [0, 255, 255],
 @ ./~/color/~/color-string/color-string.js 2:17-38
```
Any help on this would be really appreciated it.

**Comment by franceindia** [comment]
I resolved this.  Adding the fix here in case this helps anyone...

In webpack.config.js, I added the following line:

`{ test: /\.json$/, loader: "json-loader" }`

to my loader array

 ```javascript
module: {
    noParse: [
      /node-uuid/
    ],
    loaders: [
      { test: /\.json$/, loader: "json-loader" }
    ]
```

I had it in there before but it was set to exclude node_modules.

**Comment by loktar00** [comment]
:+1: thanks for this couldn't figure out wth was going on.

**Comment by jacobrask** [comment]
Is it really resolved if you need a custom webpack config for it to work?

**Comment by rgbkrk** [comment]
Just ran into this too.

**Comment by rgbkrk** [comment]
Here's our culprit:

https://github.com/MoOx/color-name/blob/master/index.json

It's perfectly legal to require JSON from node. However, I think it's worth adapting the package to use plain JS for what's really just a pile of constants.

**Comment by rgbkrk** [comment]
Done in https://github.com/MoOx/color-name/pull/2.

**Comment by rgbkrk** [comment]
`color-name` 1.1.1 is out and will prevent this issue.

**Comment by Qix-** [comment]
Thank you for the update @rgbkrk :+1: :)
